<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-L45CF4AI" name="Zmartasweden.Zmartasweden.Zmarta_se" tests="6" failures="0" timestamp="08 Feb 2018 04:06:18 GMT" time="8.080" errors="1">
  <testcase name="VerifyPageTitle" time="0.023" classname="Zmartasweden.Zmartasweden.Zmarta_se"/>
  <testcase name="VerifyLoan" time="8.057" classname="Zmartasweden.Zmartasweden.Zmarta_se">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerExceptionat ReadExcel.Excel_Data.readData(Excel_Data.java:24)at Pageobject.Locators.ApplyLoan(Locators.java:138)at Zmartasweden.Zmartasweden.Zmarta_se.VerifyLoan(Zmarta_se.java:85)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- VerifyLoan -->
  <testcase name="VerifyPersonalInfo" time="0.000" classname="Zmartasweden.Zmartasweden.Zmarta_se">
    <skipped/>
  </testcase> <!-- VerifyPersonalInfo -->
  <testcase name="VerifyMaritalstatus" time="0.000" classname="Zmartasweden.Zmartasweden.Zmarta_se">
    <skipped/>
  </testcase> <!-- VerifyMaritalstatus -->
  <testcase name="VerifyEmploymentInfo" time="0.000" classname="Zmartasweden.Zmartasweden.Zmarta_se">
    <skipped/>
  </testcase> <!-- VerifyEmploymentInfo -->
  <testcase name="VerifyFinalLoan" time="0.000" classname="Zmartasweden.Zmartasweden.Zmarta_se">
    <skipped/>
  </testcase> <!-- VerifyFinalLoan -->
</testsuite> <!-- Zmartasweden.Zmartasweden.Zmarta_se -->
